# Generated by Django 4.2.7 on 2024-01-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('prenume', models.CharField(max_length=100)),
                ('serie', models.CharField(max_length=10)),
                ('nota', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='materii',
            name='anLicenta',
            field=models.CharField(default='2022', max_length=4),
        ),
        migrations.AddField(
            model_name='materii',
            name='studenti',
            field=models.ManyToManyField(blank=True, to='api.student'),
        ),
    ]
